title: Liu-Shuaixin's Homepage
page-top-title: Shuaixin Liu
top-section-bg-text: Computer Vision
home-subtitle: Shuaixin Liu&ensp;|&ensp;刘帅鑫
copyright-text: '&copy; Shuaixin Liu 2023-2024. All Rights Reserved.'
